# -*- coding: utf-8 -*-
"""MLP_pixels.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJfQ56jBkLSq3pqAv1LxHVsVAUKrb1nh
"""

import os
import torch
from torch import nn
from torchvision.datasets import MNIST
from torch.utils.data import DataLoader
from torch.utils.data import random_split
from torchvision import transforms

import matplotlib.pyplot as plt
import math
import tqdm
from tqdm import tqdm
import numpy as np


class MLP(nn.Module):
  '''
    Multilayer Perceptron.
  '''
  def __init__(self,config):
    super().__init__()
    self.layers = nn.Sequential(
      #nn.Flatten(),                   # on vectorise les entrées si ce n'est pas le cas
      nn.Linear(config['input_features'], config['hidden_size']),
      nn.ReLU(), #nn.Sigmoid(), nn.ReLU()
      #nn.Linear(128,128),
      #nn.Sigmoid(), #nn.Sigmoid(), nn.ReLU()
      nn.Linear(config['hidden_size'], config['N_classes']*config['n_states'])
    )

  def forward(self, x):      # l'activation softmax est mise automatiquement dans la loss CrossEntropy
    '''Forward pass'''       # il faut l'ajouter au moment du test si on le souhaite
    return self.layers(x)    # voir la méthode def perf_loop(dataloader, model):
        
  #########################################################
  def pred_on_seq(self,data, symbol_n_states):
      T = data.shape[0]
      prob_pred = np.zeros((T,symbol_n_states))
      
      data=torch.from_numpy(data)
      with torch.no_grad():
          pred = self.forward(data.float())
          prob_pred = nn.Softmax(dim=1)(pred)
      return prob_pred.numpy()

#########################################################
def train_on_batch(X,y, my_model, loss_fn, optimizer):
    batch_loss = 0
    X = torch.from_numpy(X)
    y = torch.from_numpy(y)
    pred = my_model(X.float())
    loss = loss_fn(pred, y)
    batch_loss = loss.item()

    # Backpropagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    return batch_loss

def count_parameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)
